# Diccionario común para codigos INDEC
codigo_provincias_normalizado = {
    "Nacion": 1,
    "Ciudad de Buenos Aires": 2,
    "Buenos Aires": 6,
    "Catamarca": 10,
    "Cordoba": 14,
    "Corrientes": 18,
    "Chaco": 22,
    "Chubut": 26,
    "Entre Rios": 30,
    "Formosa": 34,
    "Jujuy": 38,
    "La Pampa": 42,
    "La Rioja": 46,
    "Mendoza": 50,
    "Misiones": 54,
    "Neuquen": 58,
    "Rio Negro": 62,
    "Salta": 66,
    "San Juan": 70,
    "San Luis": 74,
    "Santa Cruz": 78,
    "Santa Fe": 82,
    "Santiago Del Estero": 86,
    "Tucuman": 90,
    "Tierra Del Fuego": 94
}
